import db from "@/utils/db.js";

export default {
	createTable() {
		db.executeSql(`DROP TABLE IF EXISTS project_flanges`); // 刷新一下表, 不要就注释了
		return db.executeSql(`
			CREATE TABLE IF NOT EXISTS project_flanges (
			project_flange_id INTEGER PRIMARY KEY,
			    project_id INTEGER,
			    flange_id INTEGER,
			    unit_name TEXT,
			    equipment_name TEXT,
			    flange_name TEXT,
			    flange_no TEXT,
			    finish_picture_parts TEXT,
			    dept_id INTEGER,
			    dept_name TEXT,
			    project_type TEXT,
			    task_id INTEGER,
			    del_flag TEXT,
			    air_ldar_max REAL,
			    liquid_ldar_max REAL,
			    is_confirm TEXT,
			    average_torque REAL,
			    unit_no TEXT,
			    equipment_num TEXT,
			    flange_memo TEXT,
			    flange_spec TEXT,
			    bolt_num INTEGER,
			    rec_torque REAL,
			    risk_grade TEXT,
			    medium TEXT,
			    operate_temp REAL,
			    operate_press REAL,
			    syn_method TEXT,
			    fasten_method TEXT,
			    torque REAL,
			    angle INTEGER,
			    rel INTEGER,
			    fastener TEXT,
			    preload_torque REAL,
			    turn_angle REAL,
			    speed TEXT,
			    torque_limit REAL,
			    rotations INTEGER,
				maxFasteningRounds INTEGER,
				targetTorque REAL,
				fitTorque REAL,
				minAngle REAL,
				maxAngle REAL,
				minTorque REAL,
				maxTorque REAL,
				returnTorque REAL,
				targetAngle REAL,
				boltStatus TEXT,
			    create_by TEXT,
			    create_time TEXT,
			    update_by TEXT,
			    update_time TEXT,
			    remark TEXT,
				description TEXT
			)
		`);
	},
	//插入从后端获取的数据
	//info是后端传来的对象数组
	async insertBackData(info) {
		//表的列名
		const column = [
			"project_flange_id",
			"project_id",
			"flange_id",
			"unit_name",
			"equipment_name",
			"flange_name",
			"flange_no",
			"finish_picture_parts",
			"dept_id",
			"dept_name",
			"project_type",
			"task_id",
			"del_flag",
			"air_ldar_max",
			"liquid_ldar_max",
			"is_confirm",
			"average_torque",
			"unit_no",
			"equipment_num",
			"flange_memo",
			"flange_spec",
			"bolt_num",
			"rec_torque",
			"risk_grade",
			"medium",
			"operate_temp",
			"operate_press",
			"syn_method",
			"fasten_method",
			"torque",
			"angle",
			"rel",
			"fastener",
			"preload_torque",
			"turn_angle",
			"speed",
			"torque_limit",
			"rotations",
			"maxFasteningRounds",
			"targetTorque",
			"fitTorque",
			"minAngle",
			"maxAngle",
			"minTorque",
			"maxTorque",
			"returnTorque",
			"targetAngle",
			"boltStatus",
			"create_by",
			"create_time",
			"update_by",
			"update_time",
			"remark",
			"description"
		];
		const data = camelToSnake(info); // 后端数据可能是驼峰命名 把驼峰命名改成蛇形下划线命名
		await db.insertByColumn('project_flanges', column, data);
	}
}
